"""initial schema

Revision ID: 62cb2cddae24
Revises: 
Create Date: 2026-01-30 18:44:52.741989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cb2cddae24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jezyki',
    sa.Column('jezyk_id', sa.Integer(), nullable=False),
    sa.Column('jezyk_nazwa', sa.Text(), nullable=False),
    sa.Column('jezyk_kod', sa.String(length=2), nullable=True),
    sa.Column('jezyk_rodzina', sa.Text(), nullable=True),
    sa.Column('przyklad_polski', sa.Text(), nullable=True),
    sa.Column('przyklad_docelowy', sa.Text(), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('jezyk_id')
    )
    op.create_table('panstwa',
    sa.Column('PANSTWO_ID', sa.Integer(), nullable=False),
    sa.Column('panstwo_nazwa', sa.String(length=255), nullable=True),
    sa.Column('panstwo_kod', sa.String(length=255), nullable=True),
    sa.Column('panstwo_pelna_nazwa', sa.String(length=255), nullable=True),
    sa.Column('panstwo_ustroj', sa.String(length=255), nullable=True),
    sa.Column('panstwo_stolica', sa.String(length=255), nullable=True),
    sa.Column('panstwo_populacja', sa.BigInteger(), nullable=True),
    sa.Column('panstwo_PKB', sa.BigInteger(), nullable=True),
    sa.Column('panstwo_PKB_per_capita', sa.BigInteger(), nullable=True),
    sa.Column('panstwo_waluta', sa.String(length=255), nullable=True),
    sa.Column('panstwo_jezyk', sa.String(length=255), nullable=True),
    sa.Column('panstwo_religia', sa.String(length=255), nullable=True),
    sa.Column('kontynent', sa.String(length=255), nullable=True),
    sa.Column('panstwo_powierzchnia', sa.BigInteger(), nullable=True),
    sa.Column('panstwo_opis', sa.Text(), nullable=True),
    sa.Column('opis_updated_at', sa.DateTime(), nullable=True),
    sa.Column('czy_suwerenny', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('PANSTWO_ID')
    )
    op.create_table('religia',
    sa.Column('religia_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('religia_nazwa', sa.String(length=255), nullable=False),
    sa.Column('religia_typ', sa.Enum('monoteistyczna', 'politeistyczna', 'henoteistyczna', 'panteistyczna', 'nonteistyczna', name='religia_typ_enum'), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('religia_obraz', sa.LargeBinary(), nullable=True),
    sa.Column('religia_obraz_mime', sa.String(length=100), nullable=True),
    sa.Column('religia_nadrzedna_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['religia_nadrzedna_id'], ['religia.religia_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('religia_id'),
    sa.UniqueConstraint('religia_nazwa')
    )
    op.create_table('gospodarka',
    sa.Column('gospodarka_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=False),
    sa.Column('wzrost_pkb', sa.Float(), nullable=True),
    sa.Column('bezrobocie', sa.Float(), nullable=True),
    sa.Column('sektor_uslugi_pct', sa.Float(), nullable=True),
    sa.Column('sektor_przemysl_pct', sa.Float(), nullable=True),
    sa.Column('sektor_rolnictwo_pct', sa.Float(), nullable=True),
    sa.Column('eksport_wartosc', sa.BigInteger(), nullable=True),
    sa.Column('import_wartosc', sa.BigInteger(), nullable=True),
    sa.Column('ropa_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('gaz_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('wegiel_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('uran_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('zloto_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('kerbit_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('natsyt_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('cemium_wydobycie', sa.BigInteger(), nullable=True),
    sa.Column('technologie_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('uzbrojenie_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('budownictwo_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('przemysl_ciezki_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('przemysl_lekki_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('produkcja_zywnosci_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('uslugi_finansowe_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('przemysl_farmaceut_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('przemysl_samochodowy_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('przemysl_rozrywkowy_wartosc_prod', sa.BigInteger(), nullable=True),
    sa.Column('dlug_pct_pkb', sa.Float(), nullable=True),
    sa.Column('energia_nieodnawialne_pct', sa.Float(), nullable=True),
    sa.Column('energia_odnawialne_pct', sa.Float(), nullable=True),
    sa.Column('energia_atomowa_pct', sa.Float(), nullable=True),
    sa.Column('indeks_stabilnosci_gosp', sa.Float(), nullable=True),
    sa.Column('indeks_korupcji_gosp', sa.Float(), nullable=True),
    sa.Column('indeks_innowacji_gosp', sa.Float(), nullable=True),
    sa.Column('indeks_rozwoju_ludzkiego', sa.Float(), nullable=True),
    sa.Column('data_aktualizacji', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gospodarka_id')
    )
    op.create_table('jezyki_per_panstwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=False),
    sa.Column('jezyk_urzedowy1', sa.Integer(), nullable=True),
    sa.Column('jezyk_urzedowy2', sa.Integer(), nullable=True),
    sa.Column('jezyk_urzedowy3', sa.Integer(), nullable=True),
    sa.Column('jezyk_mniejszosciowy1', sa.Integer(), nullable=True),
    sa.Column('jezyk_mniejszosciowy2', sa.Integer(), nullable=True),
    sa.Column('jezyk_mniejszosciowy3', sa.Integer(), nullable=True),
    sa.Column('jezyk_mniejszosciowy4', sa.Integer(), nullable=True),
    sa.Column('jezyk_mniejszosciowy5', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jezyk_mniejszosciowy1'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_mniejszosciowy2'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_mniejszosciowy3'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_mniejszosciowy4'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_mniejszosciowy5'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_urzedowy1'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_urzedowy2'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['jezyk_urzedowy3'], ['jezyki.jezyk_id'], ),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panstwo_id')
    )
    op.create_table('regiony',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=True),
    sa.Column('region_nazwa', sa.String(length=255), nullable=True),
    sa.Column('region_populacja', sa.BigInteger(), nullable=True),
    sa.Column('region_ludnosc_pozamiejska', sa.BigInteger(), nullable=False),
    sa.Column('region_mapa', sa.LargeBinary(), nullable=True),
    sa.Column('region_mapa_mime', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('religia_per_panstwo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=False),
    sa.Column('religia_id', sa.Integer(), nullable=False),
    sa.Column('udzial_proc', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('dominujaca', 'oficjalna', 'mniejszosciowa', 'historyczna', name='religia_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['religia_id'], ['religia.religia_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panstwo_id', 'religia_id', name='uq_religia_per_panstwo')
    )
    op.create_table('stosunki',
    sa.Column('PANSTWO_ID', sa.Integer(), nullable=False),
    sa.Column('PANSTWO_ID2', sa.Integer(), nullable=False),
    sa.Column('relacja', sa.Enum('sojusznicze', 'partnerskie_strategiczne', 'partnerskie', 'przyjazne', 'dobre', 'neutralne', 'chlodne', 'zle', 'napiete', 'wrogie', 'egzystencjalnie_wrogie', name='relacja_enum'), nullable=False),
    sa.Column('stan', sa.Enum('pokoj', 'zwieszenie_broni', 'konflikt_dyplomatyczny', 'wojna_handlowa', 'wojna_informacyjna', 'wojna_hybrydowa', 'konflikt_kinetyczny_zamrozony', 'wojna_kinetyczna', 'okupacja', name='stan_enum'), nullable=False),
    sa.ForeignKeyConstraint(['PANSTWO_ID'], ['panstwa.PANSTWO_ID'], ),
    sa.ForeignKeyConstraint(['PANSTWO_ID2'], ['panstwa.PANSTWO_ID'], ),
    sa.PrimaryKeyConstraint('PANSTWO_ID', 'PANSTWO_ID2')
    )
    op.create_table('wojsko',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=False),
    sa.Column('wojska_ladowe_ilosc', sa.BigInteger(), nullable=True),
    sa.Column('wojska_morskie_ilosc', sa.BigInteger(), nullable=True),
    sa.Column('wojska_powietrzne_ilosc', sa.BigInteger(), nullable=True),
    sa.Column('procent_PKB', sa.Float(), nullable=True),
    sa.Column('liczba_baz_ladowych', sa.Integer(), nullable=True),
    sa.Column('liczba_baz_morskich', sa.Integer(), nullable=True),
    sa.Column('liczba_baz_powietrznych', sa.Integer(), nullable=True),
    sa.Column('czolgi_ilosc', sa.Integer(), nullable=True),
    sa.Column('mysliwce_ilosc', sa.Integer(), nullable=True),
    sa.Column('wozy_opancerzone_ilosc', sa.Integer(), nullable=True),
    sa.Column('wyrzutnie_rakiet_ilosc', sa.Integer(), nullable=True),
    sa.Column('okrety_wojenne_ilosc', sa.Integer(), nullable=True),
    sa.Column('lotniskowce_ilosc', sa.Integer(), nullable=True),
    sa.Column('okrety_podwodne_ilosc', sa.Integer(), nullable=True),
    sa.Column('drony_ilosc', sa.Integer(), nullable=True),
    sa.Column('bron_atomowa_ilosc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('panstwo_id')
    )
    op.create_table('miasta',
    sa.Column('miasto_id', sa.Integer(), nullable=False),
    sa.Column('panstwo_id', sa.Integer(), nullable=True),
    sa.Column('miasto_nazwa', sa.String(length=255), nullable=True),
    sa.Column('miasto_kod', sa.String(length=4), nullable=True),
    sa.Column('miasto_populacja', sa.Integer(), nullable=True),
    sa.Column('miasto_typ', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('czy_na_mapie', sa.Enum('TAK', 'NIE', name='czy_na_mapie_enum'), nullable=False),
    sa.Column('czy_generowane', sa.Enum('TAK', 'NIE', name='czy_generowane_enum'), nullable=False),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regiony.region_id'], ),
    sa.PrimaryKeyConstraint('miasto_id')
    )
    op.create_table('historia',
    sa.Column('HISTORIA_ID', sa.Integer(), nullable=False),
    sa.Column('data_od', sa.Date(), nullable=False),
    sa.Column('data_do', sa.Date(), nullable=True),
    sa.Column('epoka', sa.Enum('starozytna', 'sredniowieczna', 'wspolczesna', name='epoka_enum'), nullable=False),
    sa.Column('kontynent', sa.String(length=100), nullable=True),
    sa.Column('panstwo_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('miasto_id', sa.Integer(), nullable=True),
    sa.Column('nazwa_wydarzenia', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('wydarzenie_opis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['miasto_id'], ['miasta.miasto_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panstwo_id'], ['panstwa.PANSTWO_ID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regiony.region_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('HISTORIA_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia')
    op.drop_table('miasta')
    op.drop_table('wojsko')
    op.drop_table('stosunki')
    op.drop_table('religia_per_panstwo')
    op.drop_table('regiony')
    op.drop_table('jezyki_per_panstwo')
    op.drop_table('gospodarka')
    op.drop_table('religia')
    op.drop_table('panstwa')
    op.drop_table('jezyki')
    # ### end Alembic commands ###
